import type { Content, TableCell } from "pdfmake/interfaces.js";

export const buildSummary = (data: any): TableCell[][] => {
  return [
    [
      {
        text: 'SUB TOTAL:',
        colSpan: 5,
        alignment: 'right',
        bold: true,
        font: 'Helvetica',
        border: [false, false, false, false],
      },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      {
        text: '1,223,000',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '1,223,000',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
    ],
    [
      {
        text: 'DISCOUNT:',
        colSpan: 5,
        alignment: 'right',
        bold: true,
        font: 'Helvetica',
        border: [false, false, false, false],
      },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      {
        text: '',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
    ],
    [
      {
        text: 'ADMIN CHARGE:',
        colSpan: 5,
        alignment: 'right',
        bold: true,
        font: 'Helvetica',
        border: [false, false, false, false],
      },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
    ],
    [
      {
        text: 'ROUNDING:',
        colSpan: 5,
        alignment: 'right',
        bold: true,
        font: 'Helvetica',
        border: [false, false, false, false],
      },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
    ],
    [
      {
        text: 'TOTAL:',
        colSpan: 5,
        alignment: 'right',
        bold: true,
        font: 'Helvetica',
        border: [false, false, false, false],
      },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      {
        text: '1,223,000',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
    ],
    [
      {
        text: 'PAYMENT:',
        colSpan: 5,
        alignment: 'right',
        bold: true,
        font: 'Helvetica',
        border: [false, false, false, false],
      },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
    ],
    [
      {
        text: 'BALANCE:',
        colSpan: 5,
        alignment: 'right',
        bold: true,
        font: 'Helvetica',
        border: [false, false, false, false],
      },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      { text: '', border: [false, false, false, false] },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '1,223,000',
        alignment: 'right',
        border: [false, false, false, false],
      },
      {
        text: '0',
        alignment: 'right',
        border: [false, false, false, false],
      },
    ],
  ];
}